#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
                 blur_radius=50    \
                 position=top     \
                 sticky=on       \
                 padding_left=2  \
                 padding_right=2 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Bold:11.0"  \
                     icon.color=$TEXT_COLOR                 \
                     label.font="SF Pro:Bold:11.0" \
                     label.color=$TEXT_COLOR                \
                     background.border_color=$BORDER_COLOR            \
                     background.border_width=1                        \
                     background.color=$ACCENT_COLOR       \
                     background.corner_radius=14            \
                     background.height=28                  \
                     padding_left=2                        \
                     padding_right=2                       \
                     label.padding_left=0                  \
                     label.padding_right=12                \
                     icon.padding_left=12                 \
                     icon.padding_right=0

# --- Left Side Items ---
source $ITEM_DIR/spaces.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
# source $ITEM_DIR/volume.sh
source $ITEM_DIR/front_app.sh

##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
