#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

echo "loaded scripting addition"

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# for sketchybar
yabai -m config external_bar all:32:0

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 2
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 4

# center mouse on window with focus
yabai -m config mouse_follows_focus off

# Clean up empty spaces with no windows on them.
yabai -m signal --add event=space_changed action="sh ~/.config/yabai/scripts/cleanUpEmptySpaces.sh"

# focus window after active space changes
yabai -m signal --add event=space_changed action="focus_window"

# focus window after active display changes
yabai -m signal --add event=display_changed action="focus_window"

# focus on window blow cursor window/application closed
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# When a file upload page is recognized, center the window
# Center windows with AXSheet role and "" title on the screen
yabai -m rule --add role="^AXSheet$" grid=6:6:1:1:4:4 sticky=on

# ignore rules for these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="CleanShot X" manage=off mouse_follows_focus=off
yabai -m rule --add app="CustomRichPresence" manage=off mouse_follows_focus=off
yabai -m rule --add app="ChatGPT" manage=off mouse_follows_focus=off
yabai -m rule --add app="DaisyDisk" manage=off mouse_follows_focus=off
yabai -m rule --add app="^iPhone Mirroring$" manage=off mouse_follows_focus=off sticky=on
yabai -m rule --add app="^Activity Monitor$" title!="^Acitivity Monitor - All Processes$" manage=off mouse_follows_focus=off
yabai -m rule --add title='^Archive Utility$' manage=off mouse_follows_focus=off sticky=on
yabai -m rule --add title='Settings$' manage=off mouse_follows_focus=off

# for PiP
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
yabai -m rule --add title="^Picture in Picture$" manage=off mouse_follows_focus=off

# with jankyborders
borders active_color=0x80EEEEEE inactive_color=0xFF3C3C3C width=4.0 hidpi=on style=round blacklist="AXSystemDialog,Picture in Picture,iPhone Mirroring" &

echo "yabai configuration loaded"
